# Automatically generated by SST
# pylint: disable=all
from typing import Any

class Resource:
    class DATABASE_URL:
        type: str
        value: str
    class UPSTASH_REDIS_REST_TOKEN:
        type: str
        value: str
    class UPSTASH_REDIS_REST_URL:
        type: str
        value: str
    class UpdateCOE:
        name: str
        type: str
    class UpdateCars:
        name: str
        type: str
    class Updater:
        name: str
        type: str
        url: str

